//export const defaultPlaces = ['Hello', 'Coucou'];
export const defaultPlaces = [ 
    `Avion de ligne`,
    `Banque`,
    `Plage`,
    `Cathédrale`,
    `Chapiteau de cirque`,
    `Soirée d'entreprise`,
    `L'armée des croisés`,
    `Casino`,
    `Journée au spa`,
    `Ambassade`,
    `Hôpital`,
    `Hôtel`,
    `Base militaire`,
    `Studio de cinéma`,
    `Paquebot`,
    `Train de voyageurs`,
    `Bateau pirate`,
    `Station polaire`,
    `Commissariat de police`,
    `Restaurant`,
    `École`,
    `Station service`,
    `Station spatiale`,
    `Sous-marin`,
    `Supermarché`,
    `Théâtre`,
    `Université`,
    `Escouade de la seconde guerre mondiale`,
    `Piste de course`,
    `Musée d'art`,
    `Vignoble`,
    `Stade de baseball`,
    `Bibliothèque`,
    `Exposition de chats`,
    `Maison de retraite`,
    `Prison`,
    `Chantier de construction`,
    `Les Nations Unies`,
    `Fabrique de bonbons`,
    `Métro`,
    `Mine de charbon`,
    `Cimetière`,
    `Concert de rock`,
    `Club de jazz`,
    `Mariage`,
    `Station-essence`,
    `Docks du port`,
    `Bus touristique`
];